// <auto-generated />
namespace ProyectoSistemaIntegral.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Model_Usuarios : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_Usuarios));
        
        string IMigrationMetadata.Id
        {
            get { return "202012100320186_Model_Usuarios"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
