// <auto-generated />
namespace ProyectoSistemaIntegral.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Modificacion_Fecha_Ventas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modificacion_Fecha_Ventas));
        
        string IMigrationMetadata.Id
        {
            get { return "202012092127223_Modificacion_Fecha_Ventas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
